import "./globals.css";
// import { Public_Sans } from "next/font/google";

// const publicSans = Public_Sans({ subsets: ["latin"] });
import Head from "next/head";

// import '@/globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300&display=swap');
        </style> */}
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400&display=swap');
</style>
      </Head>
      <body>{children}</body>
    </html>
  );
}
